# GNUPLOT file generated by OpenCalphad
# OpenCalphad   6.004 :  2023-12-18 : with GNUPLOT map 10 fig 1
#set terminal qt size 600,500 font "Arial,16"
set terminal pdf color solid size 6,5 enhanced font "Arial,16"
set output "phase-diagram-fix.pdf"
set title "OpenCalphad   6.004 :  2023-12-18 : with GNUPLOT map 10 fig 1 \n T=Y,  P=100000, N=1, X(CR)=0.45, X(NI)=X," font "Arial,10" 
set origin 0.0, 0.0 
set size   1.0000,   1.0000
set xlabel "X(NI)"
set ylabel "Temperature/K"
set label "~O{.0  C}" at graph -0.1, -0.1 font "Garamond Bold,28"
set key top right font "Arial,12"
set linetype  1 lc rgb "#000000" lw 2 pt 10
set linetype  2 lc rgb "#4169E1" lw 2 pt 6
set linetype  3 lc rgb "#00C000" lw 2 pt 3
set linetype  4 lc rgb "#FF0000" lw 2 pt 2
set linetype  5 lc rgb "#FF00FF" lw 2 pt 4
set linetype  6 lc rgb "#C8C800" lw 2 pt 5
set linetype  7 lc rgb "#C0C0C0" lw 2 pt 7
set linetype  8 lc rgb "#00FFFF" lw 2 pt 8
set linetype  9 lc rgb "#804080" lw 2 pt 9
set linetype 10 lc rgb "#7CFF40" lw 2 pt 1
# for invariants, orange
set linetype 100 lc rgb "#FFC000" lw 3 pt 1

# Some useful GNUPLOT commands for editing the figure
# This is a dashed line (on pdf/wxt):
# set style line 15 lt 0 lc rgb "#C8C800" lw 2 pt 2

# set pointsize 0.6
# set label "text" at 0.5, 0.5 rotate by 60 font "arial,12"
# set xrange [0.5 : 0.7] 
# Adding manually a line and keep scaling:
# set multiplot
# set xrange [] writeback
#  ... plot someting
# set xrange restore
#  ... plot more using same axis scaling 
# set nomultiplot



# begin of data with lines    229
$OCT231218115141 << EOD
KEYS:  X(NI) NI2CR DELTA FCC-A1-AUTO#2 FCC-A1#1 Invariant 
 # First line:   1 BCC_A2 FCC_A1#1 NI2CR
   1    5.000000E-01    6.964785E+02 NaN  NaN  NaN  NaN 
   2    5.000025E-01    6.964849E+02 NaN  NaN  NaN  NaN 
   3    5.000525E-01    6.966123E+02 NaN  NaN  NaN  NaN 
   4    5.001525E-01    6.968671E+02 NaN  NaN  NaN  NaN 
   5    5.003525E-01    6.973763E+02 NaN  NaN  NaN  NaN 
   6    5.043525E-01    7.074356E+02 NaN  NaN  NaN  NaN 
   7    5.043927E-01    7.075356E+02 NaN  NaN  NaN  NaN 
   8    5.044056E-01    7.075676E+02 NaN  NaN  NaN  NaN 
   9    5.044314E-01    7.076316E+02 NaN  NaN  NaN  NaN 
  10    5.048343E-01    7.086316E+02 NaN  NaN  NaN  NaN 
  11    5.052383E-01    7.096316E+02 NaN  NaN  NaN  NaN 
  12    5.056431E-01    7.106316E+02 NaN  NaN  NaN  NaN 
  13    5.097448E-01    7.206316E+02 NaN  NaN  NaN  NaN 
  14    5.139458E-01    7.306316E+02 NaN  NaN  NaN  NaN 
  15    5.182502E-01    7.406316E+02 NaN  NaN  NaN  NaN 
  16    5.226624E-01    7.506316E+02 NaN  NaN  NaN  NaN 
  17    5.271869E-01    7.606316E+02 NaN  NaN  NaN  NaN 
  18    5.318285E-01    7.706316E+02 NaN  NaN  NaN  NaN 
  19    5.365926E-01    7.806316E+02 NaN  NaN  NaN  NaN 
  20    5.414844E-01    7.906316E+02 NaN  NaN  NaN  NaN 
  21    5.465098E-01    8.006316E+02 NaN  NaN  NaN  NaN 
  22    5.465149E-01    8.006416E+02 NaN  NaN  NaN  NaN 
  23    5.465658E-01    8.007416E+02 NaN  NaN  NaN  NaN 
  24    5.466678E-01    8.009416E+02 NaN  NaN  NaN  NaN 
  25    5.468718E-01    8.013416E+02 NaN  NaN  NaN  NaN 
  26    5.472806E-01    8.021416E+02 NaN  NaN  NaN  NaN 
  27    5.481009E-01    8.037416E+02 NaN  NaN  NaN  NaN 
  28    5.497523E-01    8.069416E+02 NaN  NaN  NaN  NaN 
# end of line   1    1 BCC_A2 FCC_A1#1 NI2CR

# new line   1 BCC_A2 FCC_A1#1 NI2CR
  29    5.000000E-01    6.964785E+02 NaN  NaN  NaN  NaN 
  30    4.999975E-01    6.964721E+02 NaN  NaN  NaN  NaN 
  31    4.999475E-01    6.963446E+02 NaN  NaN  NaN  NaN 
  32    4.998475E-01    6.960895E+02 NaN  NaN  NaN  NaN 
  33    4.996475E-01    6.955788E+02 NaN  NaN  NaN  NaN 
  34    4.956475E-01    6.852386E+02 NaN  NaN  NaN  NaN 
  35    4.956093E-01    6.851386E+02 NaN  NaN  NaN  NaN 
  36    4.955970E-01    6.851066E+02 NaN  NaN  NaN  NaN 
  37    4.955726E-01    6.850426E+02 NaN  NaN  NaN  NaN 
  38    4.951909E-01    6.840426E+02 NaN  NaN  NaN  NaN 
  39    4.948100E-01    6.830426E+02 NaN  NaN  NaN  NaN 
  40    4.944300E-01    6.820426E+02 NaN  NaN  NaN  NaN 
  41    4.906761E-01    6.720426E+02 NaN  NaN  NaN  NaN 
  42    4.870041E-01    6.620426E+02 NaN  NaN  NaN  NaN 
  43    4.834107E-01    6.520426E+02 NaN  NaN  NaN  NaN 
  44    4.798930E-01    6.420426E+02 NaN  NaN  NaN  NaN 
  45    4.764481E-01    6.320426E+02 NaN  NaN  NaN  NaN 
  46    4.730733E-01    6.220426E+02 NaN  NaN  NaN  NaN 
  47    4.697657E-01    6.120426E+02 NaN  NaN  NaN  NaN 
  48    4.665230E-01    6.020426E+02 NaN  NaN  NaN  NaN 
  49    4.633426E-01    5.920426E+02 NaN  NaN  NaN  NaN 
  50    4.602222E-01    5.820426E+02 NaN  NaN  NaN  NaN 
  51    4.571595E-01    5.720426E+02 NaN  NaN  NaN  NaN 
  52    4.541523E-01    5.620426E+02 NaN  NaN  NaN  NaN 
  53    4.525755E-01    5.567266E+02 NaN  NaN  NaN  NaN 
# end of line   2    1 BCC_A2 FCC_A1#1 NI2CR

# new line   2 BCC_A2 DELTA FCC_A1_AUTO#2
  54    3.999832E-01 NaN     3.800519E+02 NaN  NaN  NaN 
  55    3.999833E-01 NaN     3.800509E+02 NaN  NaN  NaN 
  56    3.999845E-01 NaN     3.800309E+02 NaN  NaN  NaN 
  57    3.999869E-01 NaN     3.799909E+02 NaN  NaN  NaN 
  58    3.999917E-01 NaN     3.799109E+02 NaN  NaN  NaN 
  59    4.000878E-01 NaN     3.783109E+02 NaN  NaN  NaN 
  60    4.002797E-01 NaN     3.751109E+02 NaN  NaN  NaN 
  61    4.006623E-01 NaN     3.687109E+02 NaN  NaN  NaN 
  62    4.012573E-01 NaN     3.587109E+02 NaN  NaN  NaN 
  63    4.018491E-01 NaN     3.487109E+02 NaN  NaN  NaN 
  64    4.024385E-01 NaN     3.387109E+02 NaN  NaN  NaN 
  65    4.030257E-01 NaN     3.287109E+02 NaN  NaN  NaN 
  66    4.036114E-01 NaN     3.187109E+02 NaN  NaN  NaN 
  67    4.041958E-01 NaN     3.087109E+02 NaN  NaN  NaN 
  68    4.047043E-01 NaN     3.000000E+02 NaN  NaN  NaN 
# end of line   3    2 BCC_A2 DELTA FCC_A1_AUTO#2

# new line   3 BCC_A2 DELTA FCC_A1_AUTO#2
  69    4.963827E-01 NaN  NaN     3.800519E+02 NaN  NaN 
  70    4.963828E-01 NaN  NaN     3.800509E+02 NaN  NaN 
  71    4.963832E-01 NaN  NaN     3.800309E+02 NaN  NaN 
  72    4.963841E-01 NaN  NaN     3.799909E+02 NaN  NaN 
  73    4.963860E-01 NaN  NaN     3.799109E+02 NaN  NaN 
  74    4.964228E-01 NaN  NaN     3.783109E+02 NaN  NaN 
  75    4.964960E-01 NaN  NaN     3.751109E+02 NaN  NaN 
  76    4.966409E-01 NaN  NaN     3.687109E+02 NaN  NaN 
  77    4.968640E-01 NaN  NaN     3.587109E+02 NaN  NaN 
  78    4.970837E-01 NaN  NaN     3.487109E+02 NaN  NaN 
  79    4.973006E-01 NaN  NaN     3.387109E+02 NaN  NaN 
  80    4.975155E-01 NaN  NaN     3.287109E+02 NaN  NaN 
  81    4.977289E-01 NaN  NaN     3.187109E+02 NaN  NaN 
  82    4.979412E-01 NaN  NaN     3.087109E+02 NaN  NaN 
  83    4.981257E-01 NaN  NaN     3.000000E+02 NaN  NaN 
# end of line   4    3 BCC_A2 DELTA FCC_A1_AUTO#2

# new line   1 BCC_A2 DELTA NI2CR
  84    4.963827E-01    3.800519E+02 NaN  NaN  NaN  NaN 
  85    4.963828E-01    3.800509E+02 NaN  NaN  NaN  NaN 
  86    4.963834E-01    3.800309E+02 NaN  NaN  NaN  NaN 
  87    4.963846E-01    3.799909E+02 NaN  NaN  NaN  NaN 
  88    4.963870E-01    3.799109E+02 NaN  NaN  NaN  NaN 
  89    4.964349E-01    3.783109E+02 NaN  NaN  NaN  NaN 
  90    4.965305E-01    3.751109E+02 NaN  NaN  NaN  NaN 
  91    4.967211E-01    3.687109E+02 NaN  NaN  NaN  NaN 
  92    4.970173E-01    3.587109E+02 NaN  NaN  NaN  NaN 
  93    4.973126E-01    3.487109E+02 NaN  NaN  NaN  NaN 
  94    4.976077E-01    3.387109E+02 NaN  NaN  NaN  NaN 
  95    4.979034E-01    3.287109E+02 NaN  NaN  NaN  NaN 
  96    4.982002E-01    3.187109E+02 NaN  NaN  NaN  NaN 
  97    4.984986E-01    3.087109E+02 NaN  NaN  NaN  NaN 
  98    4.987601E-01    3.000000E+02 NaN  NaN  NaN  NaN 
# end of line   5    1 BCC_A2 DELTA NI2CR

# new line   2 BCC_A2 DELTA NI2CR
  99    5.499942E-01 NaN     3.800519E+02 NaN  NaN  NaN 
 100    5.499942E-01 NaN     3.800509E+02 NaN  NaN  NaN 
 101    5.499942E-01 NaN     3.800309E+02 NaN  NaN  NaN 
 102    5.499942E-01 NaN     3.799909E+02 NaN  NaN  NaN 
 103    5.499942E-01 NaN     3.799109E+02 NaN  NaN  NaN 
 104    5.499946E-01 NaN     3.783109E+02 NaN  NaN  NaN 
 105    5.499952E-01 NaN     3.751109E+02 NaN  NaN  NaN 
 106    5.499963E-01 NaN     3.687109E+02 NaN  NaN  NaN 
 107    5.499976E-01 NaN     3.587109E+02 NaN  NaN  NaN 
 108    5.499984E-01 NaN     3.487109E+02 NaN  NaN  NaN 
 109    5.499990E-01 NaN     3.387109E+02 NaN  NaN  NaN 
 110    5.499994E-01 NaN     3.287109E+02 NaN  NaN  NaN 
 111    5.499997E-01 NaN     3.187109E+02 NaN  NaN  NaN 
 112    5.499998E-01 NaN     3.087109E+02 NaN  NaN  NaN 
 113    5.499999E-01 NaN     3.000000E+02 NaN  NaN  NaN 
# end of line   6    2 BCC_A2 DELTA NI2CR

# new line   3 BCC_A2 FCC_A1_AUTO#2 NI2CR
 114    5.499942E-01 NaN  NaN     3.800620E+02 NaN  NaN 
 115    5.499942E-01 NaN  NaN     3.800630E+02 NaN  NaN 
 116    5.499942E-01 NaN  NaN     3.800830E+02 NaN  NaN 
 117    5.499942E-01 NaN  NaN     3.801230E+02 NaN  NaN 
 118    5.499942E-01 NaN  NaN     3.802030E+02 NaN  NaN 
 119    5.499938E-01 NaN  NaN     3.818030E+02 NaN  NaN 
 120    5.499931E-01 NaN  NaN     3.850030E+02 NaN  NaN 
 121    5.499914E-01 NaN  NaN     3.914030E+02 NaN  NaN 
 122    5.499880E-01 NaN  NaN     4.014030E+02 NaN  NaN 
 123    5.499836E-01 NaN  NaN     4.114030E+02 NaN  NaN 
 124    5.499780E-01 NaN  NaN     4.214030E+02 NaN  NaN 
 125    5.499709E-01 NaN  NaN     4.314030E+02 NaN  NaN 
 126    5.499619E-01 NaN  NaN     4.414030E+02 NaN  NaN 
 127    5.499509E-01 NaN  NaN     4.514030E+02 NaN  NaN 
 128    5.499373E-01 NaN  NaN     4.614030E+02 NaN  NaN 
 129    5.499209E-01 NaN  NaN     4.714030E+02 NaN  NaN 
 130    5.499012E-01 NaN  NaN     4.814030E+02 NaN  NaN 
 131    5.498778E-01 NaN  NaN     4.914030E+02 NaN  NaN 
 132    5.498502E-01 NaN  NaN     5.014030E+02 NaN  NaN 
 133    5.498179E-01 NaN  NaN     5.114030E+02 NaN  NaN 
 134    5.497804E-01 NaN  NaN     5.214030E+02 NaN  NaN 
 135    5.497371E-01 NaN  NaN     5.314030E+02 NaN  NaN 
 136    5.496876E-01 NaN  NaN     5.414030E+02 NaN  NaN 
 137    5.496313E-01 NaN  NaN     5.514030E+02 NaN  NaN 
 138    5.495983E-01 NaN  NaN     5.567266E+02 NaN  NaN 
# end of line   7    3 BCC_A2 FCC_A1_AUTO#2 NI2CR

# new line   1 BCC_A2 FCC_A1_AUTO#2 NI2CR
 139    3.863213E-01    5.567265E+02 NaN  NaN  NaN  NaN 
 140    3.863214E-01    5.567255E+02 NaN  NaN  NaN  NaN 
 141    3.863229E-01    5.567055E+02 NaN  NaN  NaN  NaN 
 142    3.863260E-01    5.566655E+02 NaN  NaN  NaN  NaN 
 143    3.863321E-01    5.565855E+02 NaN  NaN  NaN  NaN 
 144    3.864541E-01    5.549855E+02 NaN  NaN  NaN  NaN 
 145    3.866986E-01    5.517855E+02 NaN  NaN  NaN  NaN 
 146    3.871883E-01    5.453855E+02 NaN  NaN  NaN  NaN 
 147    3.879553E-01    5.353855E+02 NaN  NaN  NaN  NaN 
 148    3.887238E-01    5.253855E+02 NaN  NaN  NaN  NaN 
 149    3.894932E-01    5.153855E+02 NaN  NaN  NaN  NaN 
 150    3.902632E-01    5.053855E+02 NaN  NaN  NaN  NaN 
 151    3.910336E-01    4.953855E+02 NaN  NaN  NaN  NaN 
 152    3.918043E-01    4.853855E+02 NaN  NaN  NaN  NaN 
 153    3.925755E-01    4.753855E+02 NaN  NaN  NaN  NaN 
 154    3.933471E-01    4.653855E+02 NaN  NaN  NaN  NaN 
 155    3.941194E-01    4.553855E+02 NaN  NaN  NaN  NaN 
 156    3.948927E-01    4.453855E+02 NaN  NaN  NaN  NaN 
 157    3.956671E-01    4.353855E+02 NaN  NaN  NaN  NaN 
 158    3.964428E-01    4.253855E+02 NaN  NaN  NaN  NaN 
 159    3.972202E-01    4.153855E+02 NaN  NaN  NaN  NaN 
 160    3.979994E-01    4.053855E+02 NaN  NaN  NaN  NaN 
 161    3.987807E-01    3.953855E+02 NaN  NaN  NaN  NaN 
 162    3.995643E-01    3.853855E+02 NaN  NaN  NaN  NaN 
 163    3.999832E-01    3.800520E+02 NaN  NaN  NaN  NaN 
# end of line   8    1 BCC_A2 FCC_A1_AUTO#2 NI2CR

# new line   4 BCC_A2 FCC_A1#1 NI2CR
 164    5.495983E-01 NaN  NaN  NaN     5.567366E+02 NaN 
 165    5.495983E-01 NaN  NaN  NaN     5.567376E+02 NaN 
 166    5.495982E-01 NaN  NaN  NaN     5.567576E+02 NaN 
 167    5.495982E-01 NaN  NaN  NaN     5.567976E+02 NaN 
 168    5.495980E-01 NaN  NaN  NaN     5.568776E+02 NaN 
 169    5.495945E-01 NaN  NaN  NaN     5.584776E+02 NaN 
 170    5.495876E-01 NaN  NaN  NaN     5.616776E+02 NaN 
 171    5.495741E-01 NaN  NaN  NaN     5.680776E+02 NaN 
 172    5.495539E-01 NaN  NaN  NaN     5.780776E+02 NaN 
 173    5.495352E-01 NaN  NaN  NaN     5.880776E+02 NaN 
 174    5.495182E-01 NaN  NaN  NaN     5.980776E+02 NaN 
 175    5.495031E-01 NaN  NaN  NaN     6.080776E+02 NaN 
 176    5.494903E-01 NaN  NaN  NaN     6.180776E+02 NaN 
 177    5.494799E-01 NaN  NaN  NaN     6.280776E+02 NaN 
 178    5.494723E-01 NaN  NaN  NaN     6.380776E+02 NaN 
 179    5.494677E-01 NaN  NaN  NaN     6.480776E+02 NaN 
 180    5.494664E-01 NaN  NaN  NaN     6.580776E+02 NaN 
 181    5.494687E-01 NaN  NaN  NaN     6.680776E+02 NaN 
 182    5.494747E-01 NaN  NaN  NaN     6.780776E+02 NaN 
 183    5.494848E-01 NaN  NaN  NaN     6.880776E+02 NaN 
 184    5.494992E-01 NaN  NaN  NaN     6.980776E+02 NaN 
 185    5.495181E-01 NaN  NaN  NaN     7.080776E+02 NaN 
 186    5.495418E-01 NaN  NaN  NaN     7.180776E+02 NaN 
 187    5.495705E-01 NaN  NaN  NaN     7.280776E+02 NaN 
 188    5.496044E-01 NaN  NaN  NaN     7.380776E+02 NaN 
 189    5.496437E-01 NaN  NaN  NaN     7.480776E+02 NaN 
 190    5.496887E-01 NaN  NaN  NaN     7.580776E+02 NaN 
 191    5.497396E-01 NaN  NaN  NaN     7.680776E+02 NaN 
 192    5.497964E-01 NaN  NaN  NaN     7.780776E+02 NaN 
 193    5.498596E-01 NaN  NaN  NaN     7.880776E+02 NaN 
 194    5.499291E-01 NaN  NaN  NaN     7.980776E+02 NaN 
# end of line   9    4 BCC_A2 FCC_A1#1 NI2CR

# new line   3 BCC_A2 FCC_A1_AUTO#2 NI2CR
 195    5.495983E-01 NaN  NaN     5.567265E+02 NaN  NaN 
 196    5.495983E-01 NaN  NaN     5.567255E+02 NaN  NaN 
 197    5.495984E-01 NaN  NaN     5.567055E+02 NaN  NaN 
 198    5.495987E-01 NaN  NaN     5.566655E+02 NaN  NaN 
 199    5.495992E-01 NaN  NaN     5.565855E+02 NaN  NaN 
 200    5.496093E-01 NaN  NaN     5.549855E+02 NaN  NaN 
 201    5.496290E-01 NaN  NaN     5.517855E+02 NaN  NaN 
 202    5.496660E-01 NaN  NaN     5.453855E+02 NaN  NaN 
 203    5.497182E-01 NaN  NaN     5.353855E+02 NaN  NaN 
 204    5.497639E-01 NaN  NaN     5.253855E+02 NaN  NaN 
 205    5.498036E-01 NaN  NaN     5.153855E+02 NaN  NaN 
 206    5.498379E-01 NaN  NaN     5.053855E+02 NaN  NaN 
 207    5.498673E-01 NaN  NaN     4.953855E+02 NaN  NaN 
 208    5.498924E-01 NaN  NaN     4.853855E+02 NaN  NaN 
 209    5.499135E-01 NaN  NaN     4.753855E+02 NaN  NaN 
 210    5.499312E-01 NaN  NaN     4.653855E+02 NaN  NaN 
 211    5.499458E-01 NaN  NaN     4.553855E+02 NaN  NaN 
 212    5.499578E-01 NaN  NaN     4.453855E+02 NaN  NaN 
 213    5.499676E-01 NaN  NaN     4.353855E+02 NaN  NaN 
 214    5.499754E-01 NaN  NaN     4.253855E+02 NaN  NaN 
 215    5.499816E-01 NaN  NaN     4.153855E+02 NaN  NaN 
 216    5.499864E-01 NaN  NaN     4.053855E+02 NaN  NaN 
 217    5.499901E-01 NaN  NaN     3.953855E+02 NaN  NaN 
 218    5.499930E-01 NaN  NaN     3.853855E+02 NaN  NaN 
 219    5.499942E-01 NaN  NaN     3.800520E+02 NaN  NaN 
# end of line  10    3 BCC_A2 FCC_A1_AUTO#2 NI2CR

# new line 100 invariant equilibrium
 220    5.000000E-01 NaN  NaN  NaN  NaN     6.964785E+02
 221    5.000000E-01 NaN  NaN  NaN  NaN     6.964785E+02
# end of line  11  100 invariant equilibrium

# new line 100 invariant equilibrium
 222    3.999832E-01 NaN  NaN  NaN  NaN     3.800519E+02
 223    5.499942E-01 NaN  NaN  NaN  NaN     3.800519E+02
# end of line  12  100 invariant equilibrium

# new line 100 invariant equilibrium
 224    5.499942E-01 NaN  NaN  NaN  NaN     3.800620E+02
 225    5.499942E-01 NaN  NaN  NaN  NaN     3.800620E+02
# end of line  13  100 invariant equilibrium

# new line 100 invariant equilibrium
 226    3.863213E-01 NaN  NaN  NaN  NaN     5.567265E+02
 227    5.495983E-01 NaN  NaN  NaN  NaN     5.567265E+02
# end of line  14  100 invariant equilibrium

# new line 100 invariant equilibrium
 228    5.495983E-01 NaN  NaN  NaN  NaN     5.567366E+02
 229    5.495983E-01 NaN  NaN  NaN  NaN     5.567366E+02
# end of line  15  100 invariant equilibrium


EOD
plot for [i=3: 7] $OCT231218115141 using 2:i with lines ls (i-2+ 0) title columnheader(i)
